#!/bin/bash

# Task 3: Display a numbered menu of log types to choose a file to archive
echo "Select log to archive:"

# The menu options correspond to the files generated by your Python simulators
select log_file in "heart_rate_log.log" "temperature_log.log" "water_usage_log.log"; do
    if [[ -n "$log_file" ]]; then
        echo "You have selected: $log_file"
        # The 'break' command exits the menu after one selection is made
        break
    else
        echo "Invalid selection. Please choose 1, 2, or 3."
    fi
done
